apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  mongo-root-username: YWRtaW4=
  mongo-root-password: YWRtaW4xMjM0
  postgres-user: YWRtaW4=
  postgres-password: YWRtaW4xMjM0
  mssql-password: MVN0cm9uZ1B3ZCEh