apiVersion: apps/v1
kind: Deployment
metadata:
  name: authserverdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authserverdb
  template:
    metadata:
      labels:
        app: authserverdb
    spec:
      containers:
      - name: authserverdb
        image: mcr.microsoft.com/mssql/server
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secrets
                key: mssql-password
        ports:
        - containerPort: 1433

---
apiVersion: v1
kind: Service
metadata:
  name: authserverdb-service
spec:
  selector:
    app: authserverdb
  ports:
  - port: 1434
    targetPort: 1433

