apiVersion: apps/v1
kind: Deployment
metadata:
  name: basketdb
spec:
  selector:
    matchLabels:
      app: basketdb
  template:
    metadata:
      labels:
        app: basketdb
    spec:
      containers:
        - name: basketdb
          image: redis:alpine
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: basketdb-service
spec:
  selector:
    app: basketdb
  ports:
    - port: 6379
      targetPort: 6379
