apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogdb
spec:
  selector:
    matchLabels:
      app: catalogdb
  template:
    metadata:
      labels:
        app: catalogdb
    spec:
      containers:
        - name: catalogdb
          image: mongo
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: mongo-root-password
          ports:
            - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: catalogdb-service
spec:
  selector:
    app: catalogdb
  ports:
    - port: 27017
      targetPort: 27017
