apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogapi
  template:
    metadata:
      labels:
        app: catalogapi
    spec:
      containers:
        - name: catalogapi
          image: lasting/catalogapi
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                configMapKeyRef:
                  name: configmaps
                  key: catalogapi_connectionstring
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: catalogapi-service
spec:
  type: LoadBalancer
  selector:
    app: catalogapi
  ports:
    - port: 8000
      targetPort: 80
