apiVersion: apps/v1
kind: Deployment
metadata:
  name: discountapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discountapi
  template:
    metadata:
      labels:
        app: discountapi
    spec:
      containers:
        - name: discountapi
          image: lasting/discountapi
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                configMapKeyRef:
                  name: configmaps
                  key: discountapi_connectionstring
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: discountapi-service
spec:
  type: LoadBalancer
  selector:
    app: discountapi
  ports:
    - port: 8002
      targetPort: 80
